apiVersion: v1
kind: Pod 
metadata:
  name: academy
  labels:
    app: code-server
spec:
  containers:
  - name: code-server
    imagePullPolicy: IfNotPresent
    image: pltkrt/cs:latest
    ports:
    - name: web
      containerPort: 8443
      protocol: TCP
    volumeMounts:
      - mountPath: /tmp/pk
        name: pkvol 
    securityContext:
      privileged: true
      runAsUser: 0
  imagePullSecrets:
  - name: dockercred
  initContainers:
  - name: init-code-server
    image: pltkrt/cs:latest
    command: ['sh', '-c', 'echo "hello from init" && touch /tmp/pk/test.txt']
    volumeMounts:
      - mountPath: /tmp/pk
        name: pkvol    
      #env:
          #- name: PUID
          #  value: "1000"
          #- name: PGID
          #  value: "1000"
          #- name: TZ
          #  value: "ETC/UTC"
  volumes:
  - name: pkvol 
    hostPath:
      path: /tmp/pk
  restartPolicy: Always
